export const objectGreyAnatomy = [
    {
        characterName: 'Meredith Grey',
        maritalStatus: 'Widowed',
        spouseCharacterName: 'Derek Shepherd',
        childrenNames: [
            'Zola Grey Shepherd',
            'Derek Bailey Shepherd',
            'Ellis Shepherd',
        ],
        actressName: 'Ellen Pompeo',
    },
    {
        characterName: 'Alex Karev',
        maritalStatus: 'Married',
        spouseCharacterName: 'Jo Wilson',
        childrenNames: [],
        actressName: 'Justin Chambers',
    },
    {
        characterName: 'Miranda Bailey',
        maritalStatus: 'Married',
        spouseCharacterName: 'Ben Warren',
        childrenNames: ['Tuck'],
        actressName: 'Chandra Wilson',
    },
    {
        characterName: 'Richard Webber',
        maritalStatus: 'Divorced',
        spouseCharacterName: 'Adele Webber',
        childrenNames: ['Maggie Pierce'],
        actressName: 'James Pickens Jr.',
    },
    {
        characterName: 'Cristina Yang',
        maritalStatus: 'Single',
        spouseCharacterName: null,
        childrenNames: [],
        actressName: 'Sandra Oh',
    },
];

export const arrayGreyAnatomy = [
    'Meredith Grey',
    'Alex Karev',
    'Miranda Bailey',
    'Richard Webber',
    'Cristina Yang',
    'Derek Shepherd',
    'Callie Torres',
    'Arizona Robbins',
    'Mark Sloan',
    'Owen Hunt',
    'April Kepner',
    'Jackson Avery',
    'Lexie Grey',
    'Izzie Stevens',
    "George O'Malley",
    'Addison Montgomery',
    'Amelia Shepherd',
    'Maggie Pierce',
    'Nathan Riggs',
    'Teddy Altman',
    'Jo Wilson',
    'Andrew DeLuca',
    'Stephanie Edwards',
    'Ben Warren',
];
